spring.application.name=style-profile-service

spring.datasource.url=jdbc:mysql://localhost:3306/unfold?createDatabaseIfNotExist=true
spring.datasource.username=unfold
spring.datasource.password=unfold
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

unfold.allowed-origins=http://localhost:5173
